### ISSUE TITLE
Permalink changed causes 404 on old links

### ISSUE THREAD

**Issue by j-hubb** [anomalylabs/posts-module#4]
When you change the permalink structure after posts have been created, all existing posts throw a 404 (on the old urls). Once posts have been added we should either:

1. prevent the permalink from being changed
2. 301 to the new urls

**Comment by RyanThompson** [comment]
Fixed in various progress commits today.

**Comment by j-hubb** [comment]
As far as I can see this is still an issue (or maybe it's expected behaviour).

**Comment by RyanThompson** [comment]
This works:

1 - Write a post with default settings, click on the post in your table and it will go to the long permalink.
2 - Change the settings to something like {year}/{post} and save then click on the link again it will be different and resolve. Old link will NOT resolve anymore.
